/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as DeveloperRouteImport } from './routes/developer'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as QuizzesQuizIdRouteImport } from './routes/quizzes.$quizId'
import { Route as PapersPaperIdRouteImport } from './routes/papers.$paperId'
import { Route as NotesNoteIdRouteImport } from './routes/notes.$noteId'
import { Route as AuthCallbackRouteImport } from './routes/auth_.callback'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBookmarksRouteImport } from './routes/_authenticated/bookmarks'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as CoursesCourseSlugIndexRouteImport } from './routes/courses.$courseSlug.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminTagsRouteImport } from './routes/_authenticated/admin/tags'
import { Route as AuthenticatedAdminSubjectsRouteImport } from './routes/_authenticated/admin/subjects'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminQuizzesRouteImport } from './routes/_authenticated/admin/quizzes'
import { Route as AuthenticatedAdminPapersRouteImport } from './routes/_authenticated/admin/papers'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin/media'
import { Route as AuthenticatedAdminInboxRouteImport } from './routes/_authenticated/admin/inbox'
import { Route as AuthenticatedAdminHomepageRouteImport } from './routes/_authenticated/admin/homepage'
import { Route as AuthenticatedAdminExplorerRouteImport } from './routes/_authenticated/admin/explorer'
import { Route as AuthenticatedAdminDeveloperRouteImport } from './routes/_authenticated/admin/developer'
import { Route as AuthenticatedAdminContentRouteImport } from './routes/_authenticated/admin/content'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedAdminSuperadminRouteRouteImport } from './routes/_authenticated/admin/superadmin/route'
import { Route as CoursesCourseSlugSemesterNumberIndexRouteImport } from './routes/courses.$courseSlug.$semesterNumber.index'
import { Route as AuthenticatedAdminSuperadminIndexRouteImport } from './routes/_authenticated/admin/superadmin/index'
import { Route as AuthenticatedAdminCoursesIndexRouteImport } from './routes/_authenticated/admin/courses.index'
import { Route as CoursesCourseSlugSemesterNumberSubjectSlugRouteImport } from './routes/courses.$courseSlug.$semesterNumber.$subjectSlug'
import { Route as AuthenticatedAdminSuperadminUsersRouteImport } from './routes/_authenticated/admin/superadmin/users'
import { Route as AuthenticatedAdminSuperadminSeoRouteImport } from './routes/_authenticated/admin/superadmin/seo'
import { Route as AuthenticatedAdminSuperadminFlagsRouteImport } from './routes/_authenticated/admin/superadmin/flags'
import { Route as AuthenticatedAdminSuperadminBrandingRouteImport } from './routes/_authenticated/admin/superadmin/branding'
import { Route as AuthenticatedAdminSuperadminAuditRouteImport } from './routes/_authenticated/admin/superadmin/audit'
import { Route as AuthenticatedAdminQuizzesQuizIdRouteImport } from './routes/_authenticated/admin/quizzes.$quizId'
import { Route as AuthenticatedAdminCoursesCourseIdRouteImport } from './routes/_authenticated/admin/courses.$courseId'
import { Route as AuthenticatedAdminContentNewRouteImport } from './routes/_authenticated/admin/content.new'
import { Route as AuthenticatedAdminContentIdRouteImport } from './routes/_authenticated/admin/content.$id'
import { Route as CoursesCourseSlugSemesterNumberSubjectSlugIndexRouteImport } from './routes/courses.$courseSlug.$semesterNumber.$subjectSlug.index'
import { Route as CoursesCourseSlugSemesterNumberSubjectSlugUnitNumberRouteImport } from './routes/courses.$courseSlug.$semesterNumber.$subjectSlug.$unitNumber'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRoute = DeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesQuizIdRoute = QuizzesQuizIdRouteImport.update({
  id: '/quizzes/$quizId',
  path: '/quizzes/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)
const PapersPaperIdRoute = PapersPaperIdRouteImport.update({
  id: '/papers/$paperId',
  path: '/papers/$paperId',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesNoteIdRoute = NotesNoteIdRouteImport.update({
  id: '/notes/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth_/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookmarksRoute = AuthenticatedBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CoursesCourseSlugIndexRoute = CoursesCourseSlugIndexRouteImport.update({
  id: '/courses/$courseSlug/',
  path: '/courses/$courseSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminTagsRoute = AuthenticatedAdminTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSubjectsRoute =
  AuthenticatedAdminSubjectsRouteImport.update({
    id: '/subjects',
    path: '/subjects',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminQuizzesRoute =
  AuthenticatedAdminQuizzesRouteImport.update({
    id: '/quizzes',
    path: '/quizzes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPapersRoute =
  AuthenticatedAdminPapersRouteImport.update({
    id: '/papers',
    path: '/papers',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminInboxRoute = AuthenticatedAdminInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminHomepageRoute =
  AuthenticatedAdminHomepageRouteImport.update({
    id: '/homepage',
    path: '/homepage',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminExplorerRoute =
  AuthenticatedAdminExplorerRouteImport.update({
    id: '/explorer',
    path: '/explorer',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDeveloperRoute =
  AuthenticatedAdminDeveloperRouteImport.update({
    id: '/developer',
    path: '/developer',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminContentRoute =
  AuthenticatedAdminContentRouteImport.update({
    id: '/content',
    path: '/content',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminSuperadminRouteRoute =
  AuthenticatedAdminSuperadminRouteRouteImport.update({
    id: '/superadmin',
    path: '/superadmin',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const CoursesCourseSlugSemesterNumberIndexRoute =
  CoursesCourseSlugSemesterNumberIndexRouteImport.update({
    id: '/courses/$courseSlug/$semesterNumber/',
    path: '/courses/$courseSlug/$semesterNumber/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminSuperadminIndexRoute =
  AuthenticatedAdminSuperadminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminSuperadminRouteRoute,
  } as any)
const AuthenticatedAdminCoursesIndexRoute =
  AuthenticatedAdminCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const CoursesCourseSlugSemesterNumberSubjectSlugRoute =
  CoursesCourseSlugSemesterNumberSubjectSlugRouteImport.update({
    id: '/courses/$courseSlug/$semesterNumber/$subjectSlug',
    path: '/courses/$courseSlug/$semesterNumber/$subjectSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminSuperadminUsersRoute =
  AuthenticatedAdminSuperadminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedAdminSuperadminRouteRoute,
  } as any)
const AuthenticatedAdminSuperadminSeoRoute =
  AuthenticatedAdminSuperadminSeoRouteImport.update({
    id: '/seo',
    path: '/seo',
    getParentRoute: () => AuthenticatedAdminSuperadminRouteRoute,
  } as any)
const AuthenticatedAdminSuperadminFlagsRoute =
  AuthenticatedAdminSuperadminFlagsRouteImport.update({
    id: '/flags',
    path: '/flags',
    getParentRoute: () => AuthenticatedAdminSuperadminRouteRoute,
  } as any)
const AuthenticatedAdminSuperadminBrandingRoute =
  AuthenticatedAdminSuperadminBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => AuthenticatedAdminSuperadminRouteRoute,
  } as any)
const AuthenticatedAdminSuperadminAuditRoute =
  AuthenticatedAdminSuperadminAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedAdminSuperadminRouteRoute,
  } as any)
const AuthenticatedAdminQuizzesQuizIdRoute =
  AuthenticatedAdminQuizzesQuizIdRouteImport.update({
    id: '/$quizId',
    path: '/$quizId',
    getParentRoute: () => AuthenticatedAdminQuizzesRoute,
  } as any)
const AuthenticatedAdminCoursesCourseIdRoute =
  AuthenticatedAdminCoursesCourseIdRouteImport.update({
    id: '/courses/$courseId',
    path: '/courses/$courseId',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminContentNewRoute =
  AuthenticatedAdminContentNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminContentRoute,
  } as any)
const AuthenticatedAdminContentIdRoute =
  AuthenticatedAdminContentIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminContentRoute,
  } as any)
const CoursesCourseSlugSemesterNumberSubjectSlugIndexRoute =
  CoursesCourseSlugSemesterNumberSubjectSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CoursesCourseSlugSemesterNumberSubjectSlugRoute,
  } as any)
const CoursesCourseSlugSemesterNumberSubjectSlugUnitNumberRoute =
  CoursesCourseSlugSemesterNumberSubjectSlugUnitNumberRouteImport.update({
    id: '/$unitNumber',
    path: '/$unitNumber',
    getParentRoute: () => CoursesCourseSlugSemesterNumberSubjectSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/developer': typeof DeveloperRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/bookmarks': typeof AuthenticatedBookmarksRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/help': typeof AuthenticatedHelpRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/papers/$paperId': typeof PapersPaperIdRoute
  '/quizzes/$quizId': typeof QuizzesQuizIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/admin/superadmin': typeof AuthenticatedAdminSuperadminRouteRouteWithChildren
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/content': typeof AuthenticatedAdminContentRouteWithChildren
  '/admin/developer': typeof AuthenticatedAdminDeveloperRoute
  '/admin/explorer': typeof AuthenticatedAdminExplorerRoute
  '/admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/admin/inbox': typeof AuthenticatedAdminInboxRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/papers': typeof AuthenticatedAdminPapersRoute
  '/admin/quizzes': typeof AuthenticatedAdminQuizzesRouteWithChildren
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/subjects': typeof AuthenticatedAdminSubjectsRoute
  '/admin/tags': typeof AuthenticatedAdminTagsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/courses/$courseSlug/': typeof CoursesCourseSlugIndexRoute
  '/admin/content/$id': typeof AuthenticatedAdminContentIdRoute
  '/admin/content/new': typeof AuthenticatedAdminContentNewRoute
  '/admin/courses/$courseId': typeof AuthenticatedAdminCoursesCourseIdRoute
  '/admin/quizzes/$quizId': typeof AuthenticatedAdminQuizzesQuizIdRoute
  '/admin/superadmin/audit': typeof AuthenticatedAdminSuperadminAuditRoute
  '/admin/superadmin/branding': typeof AuthenticatedAdminSuperadminBrandingRoute
  '/admin/superadmin/flags': typeof AuthenticatedAdminSuperadminFlagsRoute
  '/admin/superadmin/seo': typeof AuthenticatedAdminSuperadminSeoRoute
  '/admin/superadmin/users': typeof AuthenticatedAdminSuperadminUsersRoute
  '/courses/$courseSlug/$semesterNumber/$subjectSlug': typeof CoursesCourseSlugSemesterNumberSubjectSlugRouteWithChildren
  '/admin/courses/': typeof AuthenticatedAdminCoursesIndexRoute
  '/admin/superadmin/': typeof AuthenticatedAdminSuperadminIndexRoute
  '/courses/$courseSlug/$semesterNumber/': typeof CoursesCourseSlugSemesterNumberIndexRoute
  '/courses/$courseSlug/$semesterNumber/$subjectSlug/$unitNumber': typeof CoursesCourseSlugSemesterNumberSubjectSlugUnitNumberRoute
  '/courses/$courseSlug/$semesterNumber/$subjectSlug/': typeof CoursesCourseSlugSemesterNumberSubjectSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/developer': typeof DeveloperRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/bookmarks': typeof AuthenticatedBookmarksRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/help': typeof AuthenticatedHelpRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/papers/$paperId': typeof PapersPaperIdRoute
  '/quizzes/$quizId': typeof QuizzesQuizIdRoute
  '/courses': typeof CoursesIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/content': typeof AuthenticatedAdminContentRouteWithChildren
  '/admin/developer': typeof AuthenticatedAdminDeveloperRoute
  '/admin/explorer': typeof AuthenticatedAdminExplorerRoute
  '/admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/admin/inbox': typeof AuthenticatedAdminInboxRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/papers': typeof AuthenticatedAdminPapersRoute
  '/admin/quizzes': typeof AuthenticatedAdminQuizzesRouteWithChildren
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/subjects': typeof AuthenticatedAdminSubjectsRoute
  '/admin/tags': typeof AuthenticatedAdminTagsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/courses/$courseSlug': typeof CoursesCourseSlugIndexRoute
  '/admin/content/$id': typeof AuthenticatedAdminContentIdRoute
  '/admin/content/new': typeof AuthenticatedAdminContentNewRoute
  '/admin/courses/$courseId': typeof AuthenticatedAdminCoursesCourseIdRoute
  '/admin/quizzes/$quizId': typeof AuthenticatedAdminQuizzesQuizIdRoute
  '/admin/superadmin/audit': typeof AuthenticatedAdminSuperadminAuditRoute
  '/admin/superadmin/branding': typeof AuthenticatedAdminSuperadminBrandingRoute
  '/admin/superadmin/flags': typeof AuthenticatedAdminSuperadminFlagsRoute
  '/admin/superadmin/seo': typeof AuthenticatedAdminSuperadminSeoRoute
  '/admin/superadmin/users': typeof AuthenticatedAdminSuperadminUsersRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesIndexRoute
  '/admin/superadmin': typeof AuthenticatedAdminSuperadminIndexRoute
  '/courses/$courseSlug/$semesterNumber': typeof CoursesCourseSlugSemesterNumberIndexRoute
  '/courses/$courseSlug/$semesterNumber/$subjectSlug/$unitNumber': typeof CoursesCourseSlugSemesterNumberSubjectSlugUnitNumberRoute
  '/courses/$courseSlug/$semesterNumber/$subjectSlug': typeof CoursesCourseSlugSemesterNumberSubjectSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/developer': typeof DeveloperRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/bookmarks': typeof AuthenticatedBookmarksRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/auth_/callback': typeof AuthCallbackRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/papers/$paperId': typeof PapersPaperIdRoute
  '/quizzes/$quizId': typeof QuizzesQuizIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/_authenticated/admin/superadmin': typeof AuthenticatedAdminSuperadminRouteRouteWithChildren
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/content': typeof AuthenticatedAdminContentRouteWithChildren
  '/_authenticated/admin/developer': typeof AuthenticatedAdminDeveloperRoute
  '/_authenticated/admin/explorer': typeof AuthenticatedAdminExplorerRoute
  '/_authenticated/admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/_authenticated/admin/inbox': typeof AuthenticatedAdminInboxRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/papers': typeof AuthenticatedAdminPapersRoute
  '/_authenticated/admin/quizzes': typeof AuthenticatedAdminQuizzesRouteWithChildren
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/subjects': typeof AuthenticatedAdminSubjectsRoute
  '/_authenticated/admin/tags': typeof AuthenticatedAdminTagsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/courses/$courseSlug/': typeof CoursesCourseSlugIndexRoute
  '/_authenticated/admin/content/$id': typeof AuthenticatedAdminContentIdRoute
  '/_authenticated/admin/content/new': typeof AuthenticatedAdminContentNewRoute
  '/_authenticated/admin/courses/$courseId': typeof AuthenticatedAdminCoursesCourseIdRoute
  '/_authenticated/admin/quizzes/$quizId': typeof AuthenticatedAdminQuizzesQuizIdRoute
  '/_authenticated/admin/superadmin/audit': typeof AuthenticatedAdminSuperadminAuditRoute
  '/_authenticated/admin/superadmin/branding': typeof AuthenticatedAdminSuperadminBrandingRoute
  '/_authenticated/admin/superadmin/flags': typeof AuthenticatedAdminSuperadminFlagsRoute
  '/_authenticated/admin/superadmin/seo': typeof AuthenticatedAdminSuperadminSeoRoute
  '/_authenticated/admin/superadmin/users': typeof AuthenticatedAdminSuperadminUsersRoute
  '/courses/$courseSlug/$semesterNumber/$subjectSlug': typeof CoursesCourseSlugSemesterNumberSubjectSlugRouteWithChildren
  '/_authenticated/admin/courses/': typeof AuthenticatedAdminCoursesIndexRoute
  '/_authenticated/admin/superadmin/': typeof AuthenticatedAdminSuperadminIndexRoute
  '/courses/$courseSlug/$semesterNumber/': typeof CoursesCourseSlugSemesterNumberIndexRoute
  '/courses/$courseSlug/$semesterNumber/$subjectSlug/$unitNumber': typeof CoursesCourseSlugSemesterNumberSubjectSlugUnitNumberRoute
  '/courses/$courseSlug/$semesterNumber/$subjectSlug/': typeof CoursesCourseSlugSemesterNumberSubjectSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/developer'
    | '/mcp'
    | '/privacy'
    | '/reset-password'
    | '/setup'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/bookmarks'
    | '/dashboard'
    | '/help'
    | '/onboarding'
    | '/profile'
    | '/search'
    | '/settings'
    | '/auth/callback'
    | '/notes/$noteId'
    | '/papers/$paperId'
    | '/quizzes/$quizId'
    | '/courses/'
    | '/admin/superadmin'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/content'
    | '/admin/developer'
    | '/admin/explorer'
    | '/admin/homepage'
    | '/admin/inbox'
    | '/admin/media'
    | '/admin/papers'
    | '/admin/quizzes'
    | '/admin/settings'
    | '/admin/subjects'
    | '/admin/tags'
    | '/admin/'
    | '/courses/$courseSlug/'
    | '/admin/content/$id'
    | '/admin/content/new'
    | '/admin/courses/$courseId'
    | '/admin/quizzes/$quizId'
    | '/admin/superadmin/audit'
    | '/admin/superadmin/branding'
    | '/admin/superadmin/flags'
    | '/admin/superadmin/seo'
    | '/admin/superadmin/users'
    | '/courses/$courseSlug/$semesterNumber/$subjectSlug'
    | '/admin/courses/'
    | '/admin/superadmin/'
    | '/courses/$courseSlug/$semesterNumber/'
    | '/courses/$courseSlug/$semesterNumber/$subjectSlug/$unitNumber'
    | '/courses/$courseSlug/$semesterNumber/$subjectSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/developer'
    | '/mcp'
    | '/privacy'
    | '/reset-password'
    | '/setup'
    | '/sitemap.xml'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/bookmarks'
    | '/dashboard'
    | '/help'
    | '/onboarding'
    | '/profile'
    | '/search'
    | '/settings'
    | '/auth/callback'
    | '/notes/$noteId'
    | '/papers/$paperId'
    | '/quizzes/$quizId'
    | '/courses'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/content'
    | '/admin/developer'
    | '/admin/explorer'
    | '/admin/homepage'
    | '/admin/inbox'
    | '/admin/media'
    | '/admin/papers'
    | '/admin/quizzes'
    | '/admin/settings'
    | '/admin/subjects'
    | '/admin/tags'
    | '/admin'
    | '/courses/$courseSlug'
    | '/admin/content/$id'
    | '/admin/content/new'
    | '/admin/courses/$courseId'
    | '/admin/quizzes/$quizId'
    | '/admin/superadmin/audit'
    | '/admin/superadmin/branding'
    | '/admin/superadmin/flags'
    | '/admin/superadmin/seo'
    | '/admin/superadmin/users'
    | '/admin/courses'
    | '/admin/superadmin'
    | '/courses/$courseSlug/$semesterNumber'
    | '/courses/$courseSlug/$semesterNumber/$subjectSlug/$unitNumber'
    | '/courses/$courseSlug/$semesterNumber/$subjectSlug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/developer'
    | '/mcp'
    | '/privacy'
    | '/reset-password'
    | '/setup'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/admin'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/bookmarks'
    | '/_authenticated/dashboard'
    | '/_authenticated/help'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/auth_/callback'
    | '/notes/$noteId'
    | '/papers/$paperId'
    | '/quizzes/$quizId'
    | '/courses/'
    | '/_authenticated/admin/superadmin'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/content'
    | '/_authenticated/admin/developer'
    | '/_authenticated/admin/explorer'
    | '/_authenticated/admin/homepage'
    | '/_authenticated/admin/inbox'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/papers'
    | '/_authenticated/admin/quizzes'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/subjects'
    | '/_authenticated/admin/tags'
    | '/_authenticated/admin/'
    | '/courses/$courseSlug/'
    | '/_authenticated/admin/content/$id'
    | '/_authenticated/admin/content/new'
    | '/_authenticated/admin/courses/$courseId'
    | '/_authenticated/admin/quizzes/$quizId'
    | '/_authenticated/admin/superadmin/audit'
    | '/_authenticated/admin/superadmin/branding'
    | '/_authenticated/admin/superadmin/flags'
    | '/_authenticated/admin/superadmin/seo'
    | '/_authenticated/admin/superadmin/users'
    | '/courses/$courseSlug/$semesterNumber/$subjectSlug'
    | '/_authenticated/admin/courses/'
    | '/_authenticated/admin/superadmin/'
    | '/courses/$courseSlug/$semesterNumber/'
    | '/courses/$courseSlug/$semesterNumber/$subjectSlug/$unitNumber'
    | '/courses/$courseSlug/$semesterNumber/$subjectSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DeveloperRoute: typeof DeveloperRoute
  McpRoute: typeof McpRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  NotesNoteIdRoute: typeof NotesNoteIdRoute
  PapersPaperIdRoute: typeof PapersPaperIdRoute
  QuizzesQuizIdRoute: typeof QuizzesQuizIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  CoursesCourseSlugIndexRoute: typeof CoursesCourseSlugIndexRoute
  CoursesCourseSlugSemesterNumberSubjectSlugRoute: typeof CoursesCourseSlugSemesterNumberSubjectSlugRouteWithChildren
  CoursesCourseSlugSemesterNumberIndexRoute: typeof CoursesCourseSlugSemesterNumberIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer': {
      id: '/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes/$quizId': {
      id: '/quizzes/$quizId'
      path: '/quizzes/$quizId'
      fullPath: '/quizzes/$quizId'
      preLoaderRoute: typeof QuizzesQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/papers/$paperId': {
      id: '/papers/$paperId'
      path: '/papers/$paperId'
      fullPath: '/papers/$paperId'
      preLoaderRoute: typeof PapersPaperIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$noteId': {
      id: '/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof NotesNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/callback': {
      id: '/auth_/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookmarks': {
      id: '/_authenticated/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof AuthenticatedBookmarksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/courses/$courseSlug/': {
      id: '/courses/$courseSlug/'
      path: '/courses/$courseSlug'
      fullPath: '/courses/$courseSlug/'
      preLoaderRoute: typeof CoursesCourseSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/tags': {
      id: '/_authenticated/admin/tags'
      path: '/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AuthenticatedAdminTagsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/subjects': {
      id: '/_authenticated/admin/subjects'
      path: '/subjects'
      fullPath: '/admin/subjects'
      preLoaderRoute: typeof AuthenticatedAdminSubjectsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/quizzes': {
      id: '/_authenticated/admin/quizzes'
      path: '/quizzes'
      fullPath: '/admin/quizzes'
      preLoaderRoute: typeof AuthenticatedAdminQuizzesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/papers': {
      id: '/_authenticated/admin/papers'
      path: '/papers'
      fullPath: '/admin/papers'
      preLoaderRoute: typeof AuthenticatedAdminPapersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/inbox': {
      id: '/_authenticated/admin/inbox'
      path: '/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AuthenticatedAdminInboxRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/homepage': {
      id: '/_authenticated/admin/homepage'
      path: '/homepage'
      fullPath: '/admin/homepage'
      preLoaderRoute: typeof AuthenticatedAdminHomepageRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/explorer': {
      id: '/_authenticated/admin/explorer'
      path: '/explorer'
      fullPath: '/admin/explorer'
      preLoaderRoute: typeof AuthenticatedAdminExplorerRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/developer': {
      id: '/_authenticated/admin/developer'
      path: '/developer'
      fullPath: '/admin/developer'
      preLoaderRoute: typeof AuthenticatedAdminDeveloperRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/content': {
      id: '/_authenticated/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AuthenticatedAdminContentRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/superadmin': {
      id: '/_authenticated/admin/superadmin'
      path: '/superadmin'
      fullPath: '/admin/superadmin'
      preLoaderRoute: typeof AuthenticatedAdminSuperadminRouteRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/courses/$courseSlug/$semesterNumber/': {
      id: '/courses/$courseSlug/$semesterNumber/'
      path: '/courses/$courseSlug/$semesterNumber'
      fullPath: '/courses/$courseSlug/$semesterNumber/'
      preLoaderRoute: typeof CoursesCourseSlugSemesterNumberIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/superadmin/': {
      id: '/_authenticated/admin/superadmin/'
      path: '/'
      fullPath: '/admin/superadmin/'
      preLoaderRoute: typeof AuthenticatedAdminSuperadminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminSuperadminRouteRoute
    }
    '/_authenticated/admin/courses/': {
      id: '/_authenticated/admin/courses/'
      path: '/courses'
      fullPath: '/admin/courses/'
      preLoaderRoute: typeof AuthenticatedAdminCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/courses/$courseSlug/$semesterNumber/$subjectSlug': {
      id: '/courses/$courseSlug/$semesterNumber/$subjectSlug'
      path: '/courses/$courseSlug/$semesterNumber/$subjectSlug'
      fullPath: '/courses/$courseSlug/$semesterNumber/$subjectSlug'
      preLoaderRoute: typeof CoursesCourseSlugSemesterNumberSubjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/superadmin/users': {
      id: '/_authenticated/admin/superadmin/users'
      path: '/users'
      fullPath: '/admin/superadmin/users'
      preLoaderRoute: typeof AuthenticatedAdminSuperadminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminSuperadminRouteRoute
    }
    '/_authenticated/admin/superadmin/seo': {
      id: '/_authenticated/admin/superadmin/seo'
      path: '/seo'
      fullPath: '/admin/superadmin/seo'
      preLoaderRoute: typeof AuthenticatedAdminSuperadminSeoRouteImport
      parentRoute: typeof AuthenticatedAdminSuperadminRouteRoute
    }
    '/_authenticated/admin/superadmin/flags': {
      id: '/_authenticated/admin/superadmin/flags'
      path: '/flags'
      fullPath: '/admin/superadmin/flags'
      preLoaderRoute: typeof AuthenticatedAdminSuperadminFlagsRouteImport
      parentRoute: typeof AuthenticatedAdminSuperadminRouteRoute
    }
    '/_authenticated/admin/superadmin/branding': {
      id: '/_authenticated/admin/superadmin/branding'
      path: '/branding'
      fullPath: '/admin/superadmin/branding'
      preLoaderRoute: typeof AuthenticatedAdminSuperadminBrandingRouteImport
      parentRoute: typeof AuthenticatedAdminSuperadminRouteRoute
    }
    '/_authenticated/admin/superadmin/audit': {
      id: '/_authenticated/admin/superadmin/audit'
      path: '/audit'
      fullPath: '/admin/superadmin/audit'
      preLoaderRoute: typeof AuthenticatedAdminSuperadminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminSuperadminRouteRoute
    }
    '/_authenticated/admin/quizzes/$quizId': {
      id: '/_authenticated/admin/quizzes/$quizId'
      path: '/$quizId'
      fullPath: '/admin/quizzes/$quizId'
      preLoaderRoute: typeof AuthenticatedAdminQuizzesQuizIdRouteImport
      parentRoute: typeof AuthenticatedAdminQuizzesRoute
    }
    '/_authenticated/admin/courses/$courseId': {
      id: '/_authenticated/admin/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/admin/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedAdminCoursesCourseIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/content/new': {
      id: '/_authenticated/admin/content/new'
      path: '/new'
      fullPath: '/admin/content/new'
      preLoaderRoute: typeof AuthenticatedAdminContentNewRouteImport
      parentRoute: typeof AuthenticatedAdminContentRoute
    }
    '/_authenticated/admin/content/$id': {
      id: '/_authenticated/admin/content/$id'
      path: '/$id'
      fullPath: '/admin/content/$id'
      preLoaderRoute: typeof AuthenticatedAdminContentIdRouteImport
      parentRoute: typeof AuthenticatedAdminContentRoute
    }
    '/courses/$courseSlug/$semesterNumber/$subjectSlug/': {
      id: '/courses/$courseSlug/$semesterNumber/$subjectSlug/'
      path: '/'
      fullPath: '/courses/$courseSlug/$semesterNumber/$subjectSlug/'
      preLoaderRoute: typeof CoursesCourseSlugSemesterNumberSubjectSlugIndexRouteImport
      parentRoute: typeof CoursesCourseSlugSemesterNumberSubjectSlugRoute
    }
    '/courses/$courseSlug/$semesterNumber/$subjectSlug/$unitNumber': {
      id: '/courses/$courseSlug/$semesterNumber/$subjectSlug/$unitNumber'
      path: '/$unitNumber'
      fullPath: '/courses/$courseSlug/$semesterNumber/$subjectSlug/$unitNumber'
      preLoaderRoute: typeof CoursesCourseSlugSemesterNumberSubjectSlugUnitNumberRouteImport
      parentRoute: typeof CoursesCourseSlugSemesterNumberSubjectSlugRoute
    }
  }
}

interface AuthenticatedAdminSuperadminRouteRouteChildren {
  AuthenticatedAdminSuperadminAuditRoute: typeof AuthenticatedAdminSuperadminAuditRoute
  AuthenticatedAdminSuperadminBrandingRoute: typeof AuthenticatedAdminSuperadminBrandingRoute
  AuthenticatedAdminSuperadminFlagsRoute: typeof AuthenticatedAdminSuperadminFlagsRoute
  AuthenticatedAdminSuperadminSeoRoute: typeof AuthenticatedAdminSuperadminSeoRoute
  AuthenticatedAdminSuperadminUsersRoute: typeof AuthenticatedAdminSuperadminUsersRoute
  AuthenticatedAdminSuperadminIndexRoute: typeof AuthenticatedAdminSuperadminIndexRoute
}

const AuthenticatedAdminSuperadminRouteRouteChildren: AuthenticatedAdminSuperadminRouteRouteChildren =
  {
    AuthenticatedAdminSuperadminAuditRoute:
      AuthenticatedAdminSuperadminAuditRoute,
    AuthenticatedAdminSuperadminBrandingRoute:
      AuthenticatedAdminSuperadminBrandingRoute,
    AuthenticatedAdminSuperadminFlagsRoute:
      AuthenticatedAdminSuperadminFlagsRoute,
    AuthenticatedAdminSuperadminSeoRoute: AuthenticatedAdminSuperadminSeoRoute,
    AuthenticatedAdminSuperadminUsersRoute:
      AuthenticatedAdminSuperadminUsersRoute,
    AuthenticatedAdminSuperadminIndexRoute:
      AuthenticatedAdminSuperadminIndexRoute,
  }

const AuthenticatedAdminSuperadminRouteRouteWithChildren =
  AuthenticatedAdminSuperadminRouteRoute._addFileChildren(
    AuthenticatedAdminSuperadminRouteRouteChildren,
  )

interface AuthenticatedAdminContentRouteChildren {
  AuthenticatedAdminContentIdRoute: typeof AuthenticatedAdminContentIdRoute
  AuthenticatedAdminContentNewRoute: typeof AuthenticatedAdminContentNewRoute
}

const AuthenticatedAdminContentRouteChildren: AuthenticatedAdminContentRouteChildren =
  {
    AuthenticatedAdminContentIdRoute: AuthenticatedAdminContentIdRoute,
    AuthenticatedAdminContentNewRoute: AuthenticatedAdminContentNewRoute,
  }

const AuthenticatedAdminContentRouteWithChildren =
  AuthenticatedAdminContentRoute._addFileChildren(
    AuthenticatedAdminContentRouteChildren,
  )

interface AuthenticatedAdminQuizzesRouteChildren {
  AuthenticatedAdminQuizzesQuizIdRoute: typeof AuthenticatedAdminQuizzesQuizIdRoute
}

const AuthenticatedAdminQuizzesRouteChildren: AuthenticatedAdminQuizzesRouteChildren =
  {
    AuthenticatedAdminQuizzesQuizIdRoute: AuthenticatedAdminQuizzesQuizIdRoute,
  }

const AuthenticatedAdminQuizzesRouteWithChildren =
  AuthenticatedAdminQuizzesRoute._addFileChildren(
    AuthenticatedAdminQuizzesRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminSuperadminRouteRoute: typeof AuthenticatedAdminSuperadminRouteRouteWithChildren
  AuthenticatedAdminContentRoute: typeof AuthenticatedAdminContentRouteWithChildren
  AuthenticatedAdminDeveloperRoute: typeof AuthenticatedAdminDeveloperRoute
  AuthenticatedAdminExplorerRoute: typeof AuthenticatedAdminExplorerRoute
  AuthenticatedAdminHomepageRoute: typeof AuthenticatedAdminHomepageRoute
  AuthenticatedAdminInboxRoute: typeof AuthenticatedAdminInboxRoute
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminPapersRoute: typeof AuthenticatedAdminPapersRoute
  AuthenticatedAdminQuizzesRoute: typeof AuthenticatedAdminQuizzesRouteWithChildren
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSubjectsRoute: typeof AuthenticatedAdminSubjectsRoute
  AuthenticatedAdminTagsRoute: typeof AuthenticatedAdminTagsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCoursesCourseIdRoute: typeof AuthenticatedAdminCoursesCourseIdRoute
  AuthenticatedAdminCoursesIndexRoute: typeof AuthenticatedAdminCoursesIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminSuperadminRouteRoute:
      AuthenticatedAdminSuperadminRouteRouteWithChildren,
    AuthenticatedAdminContentRoute: AuthenticatedAdminContentRouteWithChildren,
    AuthenticatedAdminDeveloperRoute: AuthenticatedAdminDeveloperRoute,
    AuthenticatedAdminExplorerRoute: AuthenticatedAdminExplorerRoute,
    AuthenticatedAdminHomepageRoute: AuthenticatedAdminHomepageRoute,
    AuthenticatedAdminInboxRoute: AuthenticatedAdminInboxRoute,
    AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
    AuthenticatedAdminPapersRoute: AuthenticatedAdminPapersRoute,
    AuthenticatedAdminQuizzesRoute: AuthenticatedAdminQuizzesRouteWithChildren,
    AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
    AuthenticatedAdminSubjectsRoute: AuthenticatedAdminSubjectsRoute,
    AuthenticatedAdminTagsRoute: AuthenticatedAdminTagsRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
    AuthenticatedAdminCoursesCourseIdRoute:
      AuthenticatedAdminCoursesCourseIdRoute,
    AuthenticatedAdminCoursesIndexRoute: AuthenticatedAdminCoursesIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedBookmarksRoute: typeof AuthenticatedBookmarksRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedBookmarksRoute: AuthenticatedBookmarksRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CoursesCourseSlugSemesterNumberSubjectSlugRouteChildren {
  CoursesCourseSlugSemesterNumberSubjectSlugUnitNumberRoute: typeof CoursesCourseSlugSemesterNumberSubjectSlugUnitNumberRoute
  CoursesCourseSlugSemesterNumberSubjectSlugIndexRoute: typeof CoursesCourseSlugSemesterNumberSubjectSlugIndexRoute
}

const CoursesCourseSlugSemesterNumberSubjectSlugRouteChildren: CoursesCourseSlugSemesterNumberSubjectSlugRouteChildren =
  {
    CoursesCourseSlugSemesterNumberSubjectSlugUnitNumberRoute:
      CoursesCourseSlugSemesterNumberSubjectSlugUnitNumberRoute,
    CoursesCourseSlugSemesterNumberSubjectSlugIndexRoute:
      CoursesCourseSlugSemesterNumberSubjectSlugIndexRoute,
  }

const CoursesCourseSlugSemesterNumberSubjectSlugRouteWithChildren =
  CoursesCourseSlugSemesterNumberSubjectSlugRoute._addFileChildren(
    CoursesCourseSlugSemesterNumberSubjectSlugRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DeveloperRoute: DeveloperRoute,
  McpRoute: McpRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  NotesNoteIdRoute: NotesNoteIdRoute,
  PapersPaperIdRoute: PapersPaperIdRoute,
  QuizzesQuizIdRoute: QuizzesQuizIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  CoursesCourseSlugIndexRoute: CoursesCourseSlugIndexRoute,
  CoursesCourseSlugSemesterNumberSubjectSlugRoute:
    CoursesCourseSlugSemesterNumberSubjectSlugRouteWithChildren,
  CoursesCourseSlugSemesterNumberIndexRoute:
    CoursesCourseSlugSemesterNumberIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
