/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/_admin/route'
import { Route as CoursesCourseSlugIndexRouteImport } from './routes/courses.$courseSlug.index'
import { Route as AuthenticatedAdminTagsRouteImport } from './routes/_authenticated/_admin/tags'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/_admin/media'
import { Route as AuthenticatedAdminCoursesRouteImport } from './routes/_authenticated/_admin/courses'
import { Route as AuthenticatedAdminAdminRouteImport } from './routes/_authenticated/_admin/admin'
import { Route as AuthenticatedAdminSuperadminRouteRouteImport } from './routes/_authenticated/_admin/_superadmin/route'
import { Route as CoursesCourseSlugSemesterNumberIndexRouteImport } from './routes/courses.$courseSlug.$semesterNumber.index'
import { Route as CoursesCourseSlugSemesterNumberSubjectSlugRouteImport } from './routes/courses.$courseSlug.$semesterNumber.$subjectSlug'
import { Route as AuthenticatedAdminCoursesCourseIdRouteImport } from './routes/_authenticated/_admin/courses.$courseId'
import { Route as AuthenticatedAdminSuperadminSuperAdminRouteImport } from './routes/_authenticated/_admin/_superadmin/super-admin'
import { Route as AuthenticatedAdminSuperadminBrandingRouteImport } from './routes/_authenticated/_admin/_superadmin/branding'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CoursesCourseSlugIndexRoute = CoursesCourseSlugIndexRouteImport.update({
  id: '/courses/$courseSlug/',
  path: '/courses/$courseSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminTagsRoute = AuthenticatedAdminTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminCoursesRoute =
  AuthenticatedAdminCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminRoute = AuthenticatedAdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminSuperadminRouteRoute =
  AuthenticatedAdminSuperadminRouteRouteImport.update({
    id: '/_superadmin',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const CoursesCourseSlugSemesterNumberIndexRoute =
  CoursesCourseSlugSemesterNumberIndexRouteImport.update({
    id: '/courses/$courseSlug/$semesterNumber/',
    path: '/courses/$courseSlug/$semesterNumber/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoursesCourseSlugSemesterNumberSubjectSlugRoute =
  CoursesCourseSlugSemesterNumberSubjectSlugRouteImport.update({
    id: '/courses/$courseSlug/$semesterNumber/$subjectSlug',
    path: '/courses/$courseSlug/$semesterNumber/$subjectSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminCoursesCourseIdRoute =
  AuthenticatedAdminCoursesCourseIdRouteImport.update({
    id: '/$courseId',
    path: '/$courseId',
    getParentRoute: () => AuthenticatedAdminCoursesRoute,
  } as any)
const AuthenticatedAdminSuperadminSuperAdminRoute =
  AuthenticatedAdminSuperadminSuperAdminRouteImport.update({
    id: '/super-admin',
    path: '/super-admin',
    getParentRoute: () => AuthenticatedAdminSuperadminRouteRoute,
  } as any)
const AuthenticatedAdminSuperadminBrandingRoute =
  AuthenticatedAdminSuperadminBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => AuthenticatedAdminSuperadminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/courses/': typeof CoursesIndexRoute
  '/admin': typeof AuthenticatedAdminAdminRoute
  '/courses': typeof AuthenticatedAdminCoursesRouteWithChildren
  '/media': typeof AuthenticatedAdminMediaRoute
  '/tags': typeof AuthenticatedAdminTagsRoute
  '/courses/$courseSlug/': typeof CoursesCourseSlugIndexRoute
  '/branding': typeof AuthenticatedAdminSuperadminBrandingRoute
  '/super-admin': typeof AuthenticatedAdminSuperadminSuperAdminRoute
  '/courses/$courseId': typeof AuthenticatedAdminCoursesCourseIdRoute
  '/courses/$courseSlug/$semesterNumber/$subjectSlug': typeof CoursesCourseSlugSemesterNumberSubjectSlugRoute
  '/courses/$courseSlug/$semesterNumber/': typeof CoursesCourseSlugSemesterNumberIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/courses': typeof CoursesIndexRoute
  '/admin': typeof AuthenticatedAdminAdminRoute
  '/media': typeof AuthenticatedAdminMediaRoute
  '/tags': typeof AuthenticatedAdminTagsRoute
  '/courses/$courseSlug': typeof CoursesCourseSlugIndexRoute
  '/branding': typeof AuthenticatedAdminSuperadminBrandingRoute
  '/super-admin': typeof AuthenticatedAdminSuperadminSuperAdminRoute
  '/courses/$courseId': typeof AuthenticatedAdminCoursesCourseIdRoute
  '/courses/$courseSlug/$semesterNumber/$subjectSlug': typeof CoursesCourseSlugSemesterNumberSubjectSlugRoute
  '/courses/$courseSlug/$semesterNumber': typeof CoursesCourseSlugSemesterNumberIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/courses/': typeof CoursesIndexRoute
  '/_authenticated/_admin/_superadmin': typeof AuthenticatedAdminSuperadminRouteRouteWithChildren
  '/_authenticated/_admin/admin': typeof AuthenticatedAdminAdminRoute
  '/_authenticated/_admin/courses': typeof AuthenticatedAdminCoursesRouteWithChildren
  '/_authenticated/_admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/_admin/tags': typeof AuthenticatedAdminTagsRoute
  '/courses/$courseSlug/': typeof CoursesCourseSlugIndexRoute
  '/_authenticated/_admin/_superadmin/branding': typeof AuthenticatedAdminSuperadminBrandingRoute
  '/_authenticated/_admin/_superadmin/super-admin': typeof AuthenticatedAdminSuperadminSuperAdminRoute
  '/_authenticated/_admin/courses/$courseId': typeof AuthenticatedAdminCoursesCourseIdRoute
  '/courses/$courseSlug/$semesterNumber/$subjectSlug': typeof CoursesCourseSlugSemesterNumberSubjectSlugRoute
  '/courses/$courseSlug/$semesterNumber/': typeof CoursesCourseSlugSemesterNumberIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/courses/'
    | '/admin'
    | '/courses'
    | '/media'
    | '/tags'
    | '/courses/$courseSlug/'
    | '/branding'
    | '/super-admin'
    | '/courses/$courseId'
    | '/courses/$courseSlug/$semesterNumber/$subjectSlug'
    | '/courses/$courseSlug/$semesterNumber/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/courses'
    | '/admin'
    | '/media'
    | '/tags'
    | '/courses/$courseSlug'
    | '/branding'
    | '/super-admin'
    | '/courses/$courseId'
    | '/courses/$courseSlug/$semesterNumber/$subjectSlug'
    | '/courses/$courseSlug/$semesterNumber'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/_admin'
    | '/_authenticated/dashboard'
    | '/courses/'
    | '/_authenticated/_admin/_superadmin'
    | '/_authenticated/_admin/admin'
    | '/_authenticated/_admin/courses'
    | '/_authenticated/_admin/media'
    | '/_authenticated/_admin/tags'
    | '/courses/$courseSlug/'
    | '/_authenticated/_admin/_superadmin/branding'
    | '/_authenticated/_admin/_superadmin/super-admin'
    | '/_authenticated/_admin/courses/$courseId'
    | '/courses/$courseSlug/$semesterNumber/$subjectSlug'
    | '/courses/$courseSlug/$semesterNumber/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  CoursesCourseSlugIndexRoute: typeof CoursesCourseSlugIndexRoute
  CoursesCourseSlugSemesterNumberSubjectSlugRoute: typeof CoursesCourseSlugSemesterNumberSubjectSlugRoute
  CoursesCourseSlugSemesterNumberIndexRoute: typeof CoursesCourseSlugSemesterNumberIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/courses/$courseSlug/': {
      id: '/courses/$courseSlug/'
      path: '/courses/$courseSlug'
      fullPath: '/courses/$courseSlug/'
      preLoaderRoute: typeof CoursesCourseSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin/tags': {
      id: '/_authenticated/_admin/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof AuthenticatedAdminTagsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/media': {
      id: '/_authenticated/_admin/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/courses': {
      id: '/_authenticated/_admin/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AuthenticatedAdminCoursesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin': {
      id: '/_authenticated/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminAdminRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/_superadmin': {
      id: '/_authenticated/_admin/_superadmin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminSuperadminRouteRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/courses/$courseSlug/$semesterNumber/': {
      id: '/courses/$courseSlug/$semesterNumber/'
      path: '/courses/$courseSlug/$semesterNumber'
      fullPath: '/courses/$courseSlug/$semesterNumber/'
      preLoaderRoute: typeof CoursesCourseSlugSemesterNumberIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseSlug/$semesterNumber/$subjectSlug': {
      id: '/courses/$courseSlug/$semesterNumber/$subjectSlug'
      path: '/courses/$courseSlug/$semesterNumber/$subjectSlug'
      fullPath: '/courses/$courseSlug/$semesterNumber/$subjectSlug'
      preLoaderRoute: typeof CoursesCourseSlugSemesterNumberSubjectSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin/courses/$courseId': {
      id: '/_authenticated/_admin/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedAdminCoursesCourseIdRouteImport
      parentRoute: typeof AuthenticatedAdminCoursesRoute
    }
    '/_authenticated/_admin/_superadmin/super-admin': {
      id: '/_authenticated/_admin/_superadmin/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof AuthenticatedAdminSuperadminSuperAdminRouteImport
      parentRoute: typeof AuthenticatedAdminSuperadminRouteRoute
    }
    '/_authenticated/_admin/_superadmin/branding': {
      id: '/_authenticated/_admin/_superadmin/branding'
      path: '/branding'
      fullPath: '/branding'
      preLoaderRoute: typeof AuthenticatedAdminSuperadminBrandingRouteImport
      parentRoute: typeof AuthenticatedAdminSuperadminRouteRoute
    }
  }
}

interface AuthenticatedAdminSuperadminRouteRouteChildren {
  AuthenticatedAdminSuperadminBrandingRoute: typeof AuthenticatedAdminSuperadminBrandingRoute
  AuthenticatedAdminSuperadminSuperAdminRoute: typeof AuthenticatedAdminSuperadminSuperAdminRoute
}

const AuthenticatedAdminSuperadminRouteRouteChildren: AuthenticatedAdminSuperadminRouteRouteChildren =
  {
    AuthenticatedAdminSuperadminBrandingRoute:
      AuthenticatedAdminSuperadminBrandingRoute,
    AuthenticatedAdminSuperadminSuperAdminRoute:
      AuthenticatedAdminSuperadminSuperAdminRoute,
  }

const AuthenticatedAdminSuperadminRouteRouteWithChildren =
  AuthenticatedAdminSuperadminRouteRoute._addFileChildren(
    AuthenticatedAdminSuperadminRouteRouteChildren,
  )

interface AuthenticatedAdminCoursesRouteChildren {
  AuthenticatedAdminCoursesCourseIdRoute: typeof AuthenticatedAdminCoursesCourseIdRoute
}

const AuthenticatedAdminCoursesRouteChildren: AuthenticatedAdminCoursesRouteChildren =
  {
    AuthenticatedAdminCoursesCourseIdRoute:
      AuthenticatedAdminCoursesCourseIdRoute,
  }

const AuthenticatedAdminCoursesRouteWithChildren =
  AuthenticatedAdminCoursesRoute._addFileChildren(
    AuthenticatedAdminCoursesRouteChildren,
  )

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminSuperadminRouteRoute: typeof AuthenticatedAdminSuperadminRouteRouteWithChildren
  AuthenticatedAdminAdminRoute: typeof AuthenticatedAdminAdminRoute
  AuthenticatedAdminCoursesRoute: typeof AuthenticatedAdminCoursesRouteWithChildren
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminTagsRoute: typeof AuthenticatedAdminTagsRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminSuperadminRouteRoute:
      AuthenticatedAdminSuperadminRouteRouteWithChildren,
    AuthenticatedAdminAdminRoute: AuthenticatedAdminAdminRoute,
    AuthenticatedAdminCoursesRoute: AuthenticatedAdminCoursesRouteWithChildren,
    AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
    AuthenticatedAdminTagsRoute: AuthenticatedAdminTagsRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  CoursesCourseSlugIndexRoute: CoursesCourseSlugIndexRoute,
  CoursesCourseSlugSemesterNumberSubjectSlugRoute:
    CoursesCourseSlugSemesterNumberSubjectSlugRoute,
  CoursesCourseSlugSemesterNumberIndexRoute:
    CoursesCourseSlugSemesterNumberIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
