// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== 'undefined' ? createHybridAuthStorage() : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

// Storage adapter that routes reads/writes to either localStorage (persistent
// across browser restarts — "Remember me" ON) or sessionStorage (cleared when
// the tab closes — "Remember me" OFF). The mode is decided BEFORE sign-in by
// setRememberMe() below and stored in localStorage so it survives reloads.
const STORAGE_MODE_KEY = 'sb-auth-storage-mode';

function getActiveStorage(): Storage {
  try {
    return window.localStorage.getItem(STORAGE_MODE_KEY) === 'session'
      ? window.sessionStorage
      : window.localStorage;
  } catch {
    return window.localStorage;
  }
}

function createHybridAuthStorage() {
  return {
    getItem: (key: string) => {
      // Read from the active store first; fall back to the other so a
      // session started in one mode is still found if the flag flipped.
      const primary = getActiveStorage().getItem(key);
      if (primary !== null) return primary;
      const fallback =
        getActiveStorage() === window.localStorage
          ? window.sessionStorage
          : window.localStorage;
      return fallback.getItem(key);
    },
    setItem: (key: string, value: string) => {
      const active = getActiveStorage();
      active.setItem(key, value);
      // Make sure the other store doesn't hold a stale token.
      const other =
        active === window.localStorage ? window.sessionStorage : window.localStorage;
      other.removeItem(key);
    },
    removeItem: (key: string) => {
      window.localStorage.removeItem(key);
      window.sessionStorage.removeItem(key);
    },
  } satisfies {
    getItem: (k: string) => string | null;
    setItem: (k: string, v: string) => void;
    removeItem: (k: string) => void;
  };
}

/**
 * Call BEFORE supabase.auth.signInWithPassword / signInWithOtp / OAuth.
 * `true`  → persist session in localStorage (survives browser restart).
 * `false` → keep session in sessionStorage only (cleared on tab close).
 */
export function setRememberMe(remember: boolean) {
  if (typeof window === 'undefined') return;
  try {
    if (remember) {
      window.localStorage.removeItem(STORAGE_MODE_KEY);
    } else {
      window.localStorage.setItem(STORAGE_MODE_KEY, 'session');
    }
  } catch {
    /* ignore */
  }
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

